# -*- coding: utf-8 -*-
"""Logistic regression. | Iris flower.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gt5K5X7BqXSAcHVyFGJrMSqDUXM7Seui

Importing libraries and loading our data
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

"""A classifier to detect the Iris-Virginica only on the petal
width feature.
"""

iris = datasets.load_iris()

list(iris.keys())

X=iris["data"][:, 3: ] #The petal width

y=(iris["target"]==2).astype(np.int) # 1 if Iris-Virginica , else 0

"""Training logistic regression model :"""

from sklearn.linear_model import LogisticRegression

log_reg=LogisticRegression()

log_reg.fit(X,y)

X_new = np.linspace(0, 3, 1000).reshape(-1, 1)
y_proba = log_reg.predict_proba(X_new)
plt.plot(X_new,y_proba)
font1 = {'family':'serif','color':'red','size':25}
font2 = {'family':'serif','color':'blue','size':35}
font3 = {'family':'serif','color':'black','size':35}
plt.title("Logistic regression", fontdict=font3)
plt.xlabel ("Data"  , fontdict = font1)
plt.ylabel ("Target", fontdict= font2)
plt.plot(X_new, y_proba[:, 1], "g-", label="Iris-Virginica")
plt.plot(X_new, y_proba[:, 0], "b--", label="Not Iris-Virginica", linestyle="dotted")

